import os
import sys
import rtconfig

from rtconfig import RTT_ROOT

# set RTT_ROOT
#if not os.getenv("RTT_ROOT"):
#    RTT_ROOT="rt-thread"

sys.path = sys.path + [os.path.join(RTT_ROOT, 'tools')]
from building import *

TARGET = 'rtthread.' + rtconfig.TARGET_EXT

env = Environment(tools = ['mingw'],
    AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
    CC = rtconfig.CC, CCFLAGS = rtconfig.CFLAGS,
    CXX = rtconfig.CC, CXXFLAGS = rtconfig.CXXFLAGS,
    AR = rtconfig.AR, ARFLAGS = '-rc',
    LINK = rtconfig.LINK, LINKFLAGS = rtconfig.LFLAGS)
env.PrependENVPath('PATH', rtconfig.EXEC_PATH)

Export('RTT_ROOT')
Export('rtconfig')

# prepare building environment
objs = PrepareBuilding(env, RTT_ROOT, has_libcpu=True)

# make a building
DoBuilding(TARGET, objs)

env.Clean(TARGET, 'rtthread.bin')
env.Clean(TARGET, 'rtthread.map')
env.Clean(TARGET, 'rtconfig.pyc')
env.Clean(TARGET, 'rt-thread/tools/mkdist.pyc')
env.Clean(TARGET, 'rt-thread/tools/building.pyc')
env.Clean(TARGET, 'rt-thread/tools/gcc.pyc')
env.Clean(TARGET, 'rt-thread/tools/utils.pyc')
env.Clean(TARGET, '.sconsign.dblite')
env.Clean(TARGET, 'build')
